# Generated by Django 4.1 on 2022-08-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPro', '0002_news_subtitle_alter_news_images_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=400)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
