# Generated by Django 4.1 on 2022-08-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyPro', '0003_contact_alter_comments_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_replies', to='MyPro.comments'),
        ),
    ]
